// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ANOVA_cpp_2group
long double ANOVA_cpp_2group(NumericVector full_beta, NumericVector betaT, NumericVector betaR);
RcppExport SEXP _COHCAP_ANOVA_cpp_2group(SEXP full_betaSEXP, SEXP betaTSEXP, SEXP betaRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type full_beta(full_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaR(betaRSEXP);
    rcpp_result_gen = Rcpp::wrap(ANOVA_cpp_2group(full_beta, betaT, betaR));
    return rcpp_result_gen;
END_RCPP
}
// ANOVA_cpp_2group_2way
long double ANOVA_cpp_2group_2way(NumericVector full_beta, NumericVector betaT, NumericVector betaR, NumericVector interact_var);
RcppExport SEXP _COHCAP_ANOVA_cpp_2group_2way(SEXP full_betaSEXP, SEXP betaTSEXP, SEXP betaRSEXP, SEXP interact_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type full_beta(full_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaR(betaRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type interact_var(interact_varSEXP);
    rcpp_result_gen = Rcpp::wrap(ANOVA_cpp_2group_2way(full_beta, betaT, betaR, interact_var));
    return rcpp_result_gen;
END_RCPP
}
// ttest_cpp
long double ttest_cpp(NumericVector beta1, NumericVector beta2);
RcppExport SEXP _COHCAP_ttest_cpp(SEXP beta1SEXP, SEXP beta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta2(beta2SEXP);
    rcpp_result_gen = Rcpp::wrap(ttest_cpp(beta1, beta2));
    return rcpp_result_gen;
END_RCPP
}
// ttest_cpp_paired
long double ttest_cpp_paired(NumericVector paired_diff);
RcppExport SEXP _COHCAP_ttest_cpp_paired(SEXP paired_diffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type paired_diff(paired_diffSEXP);
    rcpp_result_gen = Rcpp::wrap(ttest_cpp_paired(paired_diff));
    return rcpp_result_gen;
END_RCPP
}

// lmResidual_cpp_1var
long double lmResidual_cpp_1var(NumericVector full_beta, NumericVector full_continuous);
RcppExport SEXP _COHCAP_lmResidual_cpp_1var(SEXP full_betaSEXP, SEXP full_continuousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type full_beta(full_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type full_continuous(full_continuousSEXP);
    rcpp_result_gen = Rcpp::wrap(lmResidual_cpp_1var(full_beta, full_continuous));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_COHCAP_ANOVA_cpp_2group", (DL_FUNC) &_COHCAP_ANOVA_cpp_2group, 3},
    {"_COHCAP_ANOVA_cpp_2group_2way", (DL_FUNC) &_COHCAP_ANOVA_cpp_2group_2way, 4},
    {"_COHCAP_ttest_cpp", (DL_FUNC) &_COHCAP_ttest_cpp, 2},
    {"_COHCAP_ttest_cpp_paired", (DL_FUNC) &_COHCAP_ttest_cpp_paired, 1},
	{"_COHCAP_lmResidual_cpp_1var", (DL_FUNC) &_COHCAP_lmResidual_cpp_1var, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_COHCAP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
